name: 🐛 Bug Report
description: Report an issue you encountered
title: "[BUG] : "
labels: ["bug"]
assignees: ["LilianSeon"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out this bug report as thoroughly as possible 🙏

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you experienced
      placeholder: "Example: When I click the 'Play' button, nothing happens."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Walk us through how to reproduce the bug
      placeholder: |
        1. Go to the ...
        2. Click on ...
        3. Observe the behavior
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, or app version
      placeholder: "Example: Windows 11, Chrome 112, App v1.2.0"

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add a screenshot if possible

  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description: Any other context, logs, or details that might help
