name: ❓ Question
description: Ask a question or request clarification
title: "[QUESTION] : "
labels: ["question"]
assignees: ["LilianSeon"]

body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to ask?
      placeholder: "How does something work?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve or understand?
